---
title: "readme pathlyXYZ"
author: "jmenblaz"
format: md
editor: visual
---

## pathlyXYZ · An R Package for multidimensional simulation of tracking data

***Keywords:** Movement-ecologty · Biologging · 3D-Movement · Animal-tracking · Trajectory simulation · Vertical dimension*

### Overview

**pathlyXYZ** is an open-access R package to simulate movement paths in three axis of the landdcape (X, Y, Z) for empirical bio-logging trajectories. Its main and novel feature is the ability to simulate fully 3D paths, while maintaining flexibility to implement, unify, or extend other types of path simulations such as 2-2.5D in future versions.

Animal movement occurs naturally in three dimensions, not just in a 2D plane (whether in marine, terrestrial, or aerial environments). **pathlyXYZ** is an open-access R package for simulating movement paths in three dimensions (X, Y, Z) from empirical bio-logging trajectories. Its main novelty is the ability to generate fully 3D trajectories while maintaining flexibility to implement, unify, or extend other path simulation approaches, including 2D and 2.5D simulations in coming versions.

The package has multiple cutting-edge use cases, such as, 1) **Generating pseudo-absences or background points for Species Distribution Models (SDMs)**, creating realistic null paths that respect the spatial-temporal structure of observed animal movements; **Testing habitat selection hypotheses**, by comparing observed 3D trajectories with simulated null paths to detect preferences for certain depths, heights, or locations.; or **Evaluating risk or exposure to threats**, such as fisheries, predators, or anthropogenic infrastructure, by overlaying simulated trajectories with threat maps to calculate probabilistic exposure.

These examples highlight the potential of **pathlyXYZ** to advance movement ecology by providing flexible, reproducible, and multidimensional trajectory simulation. Additionally, the package provides custom **functionalities** useful for visualization species distribution prioritizing records based on user-defined variables. These features make GeoThinneR a valuable tool for handling large-scale occurrence datasets.

## 

## Getting started

You can install **pathlyXYZ** from CRAN with:

\`\`\`{{r}} install.packages("pathlyXYZ")

To install the **development version** from GitHub, use:

\`\`\`{{r}} \# install.packages("pathlyXYZ") devtools::install_github("jmenblaz/pathlyXYZ")

------------------------------------------------------------------------

## Documentation

For detailed documentation, guides, and usage examples, please visit the official package documentation.

------------------------------------------------------------------------

## Contributing

pathlyXYZ are welcomes and open for well-intention contributions! For suggestions, improvements or new features, please open an issue or submit a pull request on its [GitHub repository](https://github.com/jmenblaz/pathlyXYZ)

------------------------------------------------------------------------

## How to cite pathlyXYZ

The pathlyXYZ manuscript is currently in progress. In the meantime, you can cite the preprint as follows:

> Menéndez-Bláquez, J. (2026). pahtlyXYZ: An R Package for path simulation of tracking data. arXiv preprint arXiv:2505.07867. DOI:
